</$objtype/mkfile

all: $O.testmp.out
# all: idris_gmp.$O idris_heap.$O

$O.testmp.out: testmp.$O
        $LD -o 8.testmp.out testmp.$O
        ./8.testmp.out

%.$O: %.c
        $CC $CFLAGS -Fvw $stem.c

install:
        mk
        # cp hello /$objtype/bin

clean:
   rm *.$O
